# Numpy

In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [6]:
a=np.array([(1,2,3,4),(5,6,7,8)])
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

## Aprendendo2

In [13]:
a=np.array([(1,2,3,4),(5,6,7,8)])
a.ndim

2

In [14]:
a=np.array([(1,2,3,4),(5,6,7,8)])
a.itemsize

8

In [15]:
a=np.array([(1,2,3,4),(5,6,7,8)])
a.dtype

dtype('int64')

In [16]:
a=np.array([(1,2,3,4),(5,6,7,8)])
a.shape

(2, 4)

In [21]:
a=np.array([(1,2,3,4),(5,6,7,8)])
a.reshape(4,2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [22]:
a=np.array([(1,2,3,4),(5,6,7,8)])
a[0,2]

3

In [23]:
a=np.array([(1,2,3,4),(5,6,7,8)])
a[0:,3]

array([4, 8])

In [24]:
a=np.linspace(1,4,20)
a

array([ 1.        ,  1.15789474,  1.31578947,  1.47368421,  1.63157895,
        1.78947368,  1.94736842,  2.10526316,  2.26315789,  2.42105263,
        2.57894737,  2.73684211,  2.89473684,  3.05263158,  3.21052632,
        3.36842105,  3.52631579,  3.68421053,  3.84210526,  4.        ])

In [26]:
a=np.linspace(1,4,6)
a.min()
a.max()
a.sum()

15.0

In [28]:
a=np.array([(1,2,3,4),(5,6,7,8)])
a.sum(axis=0)


array([ 6,  8, 10, 12])

In [29]:
a=np.array([(1,2,3,4),(5,6,7,8)])
np.sqrt(a)

array([[ 1.        ,  1.41421356,  1.73205081,  2.        ],
       [ 2.23606798,  2.44948974,  2.64575131,  2.82842712]])

In [30]:
x=np.array([(1,2,3,4),(5,6,7,8)])
y=np.array([(1,2,3,4),(5,6,7,8)])
x/y

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

### Vertical

In [35]:
x=np.array([(1,2,3,4),(5,6,7,8)])
y=np.array([(1,2,3,4),(5,6,7,8)])
np.hstack ((x,y))

array([[1, 2, 3, 4, 1, 2, 3, 4],
       [5, 6, 7, 8, 5, 6, 7, 8]])